name: CICD - MAIN
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  Build:
    uses: golive123/roboshop-github-actions/.github/workflows/ci-main.yml@main
    with:
      appType: 'maven'
      appName: 'shipping'
    secrets:
          azuresecrets: ${{ secrets.azuresecrets }}



