name: CICD - MAIN
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  Build:
    uses: udayach123/roboshop-github-actions/.github/workflows/ci-main.yml@main
    with:
      appType: '${{ inputs.appType }}'
  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - run: echo OK
  Dev_deploy:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - run: echo OK
  Qa_Deploy:
    environment: QA
    runs-on: ubuntu-latest
    needs: Dev_deploy
    steps:
      - run: echo OK
  Uat_Deploy:
    environment: UAT
    runs-on: ubuntu-latest
    needs: Qa_deploy
    steps:
      - run: echo OK
  Prod_Deploy:
    environment: PROD
    runs-on: ubuntu-latest
    needs: Uat_Deploy
    steps:
      - run: echo OK



